main/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, UserLogin, RegisterView

from django.contrib.auth.views import LogoutView

app_name = "main"
urlpatterns = [
    path('login', UserLogin.as_view(), name="login"),
    path('logout', LogoutView.as_view(next_page = 'main:login'), name="logout"),
    path('register', RegisterView.as_view(), name='register'),

    path('', TaskList.as_view(), name="tasks"),
    path('task/<int:pk>', TaskDetail.as_view(), name="detail"),
    path('task-create', TaskCreate.as_view(), name="task-create"),
    path('task-update/<int:pk>', TaskUpdate.as_view(), name="task-update"),
    path('task-delete/<int:pk>', TaskDelete.as_view(), name="task-delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db.models.deletion import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['complete']

main/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import login

from .models import Task


# Create your views here.
class UserLogin(LoginView):
    template_name = 'main/login.html'
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('main:tasks')


class RegisterView(FormView):
    template_name = 'main/register.html'
    form_class = UserCreationForm
    # redirect_authenticated_user = True
    success_url = reverse_lazy('main:tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)

        return super(RegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('main:tasks')

        return super(RegisterView, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['tasks'] = context['tasks'].filter(user = self.request.user)
        context['count'] = context['tasks'].filter(complete = False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)

        context['search_input'] = search_input

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = "task"


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('main:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('main:tasks')


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy('main:tasks')

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mali" rel="stylesheet">  
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'main/images/favicon-16x16.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'main/images/favicon-32x32.png' %}">
    <title>To Do List</title>

    <style>
      body {
        background-image: url("{% static 'main/images/sakura.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        padding-top: 50px;
      }

      .container {
        max-width: 550px;
        background-color: white;
        margin: auto;
        background-color: transparent;
      }

      .header {
        display: flex;
        justify-content: space-between;
        color: #fff;
        padding: 10px;
        border-radius: 5px 5px 0 0;
        color:  #6da9d2;
      }

      .header a {
            color: #ffb7ce;
            text-decoration: none;
      }

      .header a:hover{
        text-decoration: underline;
      }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
            overflow: hidden;

            background-color: transparent;
        }

        .task-title {
            display: flex;
            padding: 20px;
        }

        .task-title a {
            text-decoration: none;
            color: whitesmoke;
            font-weight: 800;
            font-size: large;
            margin-left: 10px;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: cornflowerblue;
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: palevioletred;
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
            padding: 20px 10px;
        }

         #add-link {
            color: #EB796F;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }

        input[type=text],
        input[type=password],
        textarea {
            margin-top: 5px;
            border-radius: 5px;
            padding: 10px;
            width: 90%;

            background-color: transparent;
            border: 2px solid #9ecaed;
            border-radius: 7px;

            font-size: 15px;
            font-family: 'Mali', cursive;
            font-weight: 300;
            color: paleturquoise;
        }

        input[type=text]:focus,
        input[type=password]:focus,
        textarea:focus { 
            outline: none;
            border-color: #9ecaed;
            box-shadow: 0 0 20px #9ecaed;
}

        label {
            padding-top: 20px !important;
            display: block;
            color: white;
            text-shadow:0 0 2px #ddd;
        }

        ::placeholder {
            font-weight: 900;
            opacity: 0.7;
        }

        .button {
            color: #EB796F;
            padding: 10px;
            font-size: 16px;
            font-weight: 700;
            cursor: pointer;
            text-decoration: none;
            margin-left: 5px;
            background-color: transparent;
            border: 1px solid white;
            border-radius: 10px;
        }

        .form{
          padding: 20px;
          backdrop-filter: blur(3px);
        }

        .login-bg{
          content: '';
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          position: absolute;
          background-image: url("{% static 'main/images/sakura.jpg' %}");
          background-size: cover;
          background-repeat: no-repeat;
          background-attachment: fixed;
          filter: blur(8px);
          z-index: -1;
        }

        .login-button{
          margin-top: 18px;
          color: aqua;
          font-size: large;
          font-weight: 700;
        }

        .login-button:hover{
          text-decoration: underline;
        }

        .log-reg{
          color: white;
          text-shadow: 2px 2px 3.5px white;
          text-decoration: underline;
        }

        p, li, h2{
           font-size: 16px; 
           color: white;
        }

        #help{
            margin-top: 14px;
            color: turquoise;
            background-color: transparent;
            border: none;
            font-weight: 600;
            font-size: 15px;
            cursor: help;
        }

        .swal-modal {
            background-image: linear-gradient(180deg, royalblue, #6FA8DC, skyblue);
            border: 1px solid white;
            box-shadow: 0 0 15px white;
        }

        .swal-title{
          color: whitesmoke;
          text-align: start;
          text-decoration: underline;
        }

        .swal-text{
          text-align: start;
          font-size: 35px;
          font-family: 'Mali';
          color: aliceblue;
        }

        .swal-button{
          background-color: #e9b1cd;
          color: azure;
          font-size: 16px;
          font-weight: 800;
        }
      
        input[type=checkbox] {
          accent-color: #138808;
        }

    </style>
  </head>
  <body>
    <div class="container">
      {% block body %} 
      {% endblock %}
    </div>
  </body>
</html>

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block body %}

<div class="login-bg">
    
</div>

<div class="form">
    <h1 class="log-reg">Login</h1>

    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button login-button" type="submit" value="Login">
    </form>

    <p>Don't have an account yet? <a href="{% url 'main:register' %}" style="text-decoration: none; color: aqua;"> Register</a> </p>
</div>

{% endblock %}

main/templates/main/register.html
{% extends 'main/base.html' %}
{% block body %}

<!-- to create the blurry background -->
<div class="login-bg">
    
</div>



<div class="form">
    <h1 class="log-reg">Register</h1>

    <form method="POST">
    {% csrf_token %}
        
        {% if form.errors %} 
        {% for field in form %} 
        {% for error in field.errors %}
            <p> {{ error }}</p> 
        {% endfor %}
        {% endfor %}
        {% endif %}
        
        <label >{{ form.username.label }}</label>
        {{ form.username }}

        <label >{{ form.password1.label }}</label>
        {{ form.password1 }}
        <p style="font-weight: 600; margin-bottom: -2px; margin-top: 5px;"> <i>Password must be atleast 8 characters long.</i>   </p>
        
        <label >{{ form.password2.label }}</label>
        {{ form.password2 }}
        
        <input class="button login-button" type="submit" value="Register">
    </form>

    <p>Already registered? <a href="{% url 'main:login' %}" style="text-decoration: none; color: aqua;"> Login</a> </p>  
</div>


{% endblock %}

main/templates/main/task_confirm_delete.html
{% extends 'main/base.html' %} {% block body %}

<div class="header">
  <a href="{% url 'main:tasks' %}">&#8592; Back</a>
</div>

<div class="form">
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete the task?</p>
    <p>Task: <span style="font-weight: bold;">{{ task }}</span></p>
    <input class="button" type="submit" value="Delete" />
  </form>
</div>

{% endblock %}

main/templates/main/task_detail.html
<h1>Task: {{ task }}</h1>

<a href="{% url 'main:tasks' %}">Go back</a>

main/templates/main/task_form.html
{% extends 'main/base.html' %} {% block body %}

<div class="header">
  <a href="{% url 'main:tasks' %}">&#8592; Back</a>
</div>

<div class="form">
  <form method="POST" action="">
    {% csrf_token %} 
    {{ form.as_p}}
    <input class="button" type="submit" value="Submit" />
  </form>
</div>

{% endblock %}

main/templates/main/task_list.html
{% extends 'main/base.html' %} {% block body %}
{% load static %}

<div class="form">

<div class="header">
  <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin: 0">You have <i style="font-weight: bold;">{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
  </div>

  {% if request.user.is_authenticated %}
  <div>
    <a href="{% url 'main:logout' %}">Logout</a>
    <br>
    <button id="help">Help</button>
  </div>
  

  {% else %}
  <a href="{% url 'main:login' %}">Login</a>

  {% endif %}
</div>

<div id="search-add-wrapper">
    <form method="GET" style="display: flex;">
        <input type='text' name='search-area' placeholder="Search your task" value="{{ search_input }}" autofocus>
        <input class="button" type="submit" value='Search'>
    </form>
    <a id="add-link" href="{% url 'main:task-create' %}">&#x2b;</a>
</div>


<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        <div class="task-title">
            {% if task.complete %}
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'main:task-update' task.id %}">{{task}}</a></s></i> 
            
            {% else %}
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'main:task-update' task.id %}">{{task}}</a> 
            {% endif %}
        </div>
        <a class="delete-link" href="{% url 'main:task-delete' task.id %}">&#215;</a>
    </div>

    {% empty %}
    <div style="text-align: center; padding-bottom: 10px; line-height: 1em;">
        <h2>No task.</h2>
    </div>
    
    {% endfor %}
</div>

</div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    let list = document.createElement('ul');
    let listItem = document.createElement('li');
    listItem.innerHTML = 'I am your content';
    list.appendChild(listItem);

    document.querySelector('button').onclick = help;

    function help(){
        swal({
            title: "Click on :-",
            text: "+ to create/add a task, x to delete the task, 'task_name' to edit the task.",
            icon: "{% static 'main/images/no-face128.png' %}",
            button: {
                text: "Got it!"
            }
        });
    }

</script>

{% endblock %}